exports.run = (client, message, args) => {
  var listOfCharacters = [
    "Bayonetta",
    "Bowser",
    "Bowser Jr.",
    "Captain Falcon",
    "Cloud",
    "Corrin",
    "Daisy",
    "Dark Pit",
    "Diddy Kong",
    "Donkey Kong",
    "Dr. Mario",
    "Duck Hunt",
    "Falco",
    "Fox",
    "Ganondorf",
    "Greninja",
    "Ice Climbers",
    "Inkling Boy and Girl",
    "Ike",
    "Jigglypuff",
    "King Dedede",
    "Kirby",
    "Link",
    "Little Mac",
    "Lucario",
    "Lucas",
    "Lucina",
    "Luigi",
    "Mario",
    "Marth",
    "Mega Man",
    "Meta Knight",
    "Mewtwo",
    "Mii Fighter",
    "Mr. Game & Watch",
    "Ness",
    "Captain Olimar",
    "Pac-Man",
    "Palutena",
    "Peach",
    "Pichu",
    "Pikachu",
    "Pit",
    "Pokémon Trainer",
    "Ridley",
    "R.O.B.",
    "Robin",
    "Rosalina",
    "Roy",
    "Ryu",
    "Samus",
    "Sheik",
    "Shulk",
    "Snake",
    "Sonic",
    "Toon Link",
    "Villager",
    "Wario",
    "Wii Fit Trainer",
    "Wolf",
    "Yoshi",
    "Young Link",
    "Zelda",
    "Zero Suit Samus",
    "Simon Belmont",
    "Richter",
    "Ken Masters",
    "Inceneroar",
    "Piranha Plant",
    "Dark Samus",
    "Chrom",
    "Simon",
    "Richter",
    "King K. Rool",
    "Isabelle",
    "Joker"
  ];
  var randomInt = Math.floor(Math.random() * listOfCharacters.length);
  return message.reply("You should main " + listOfCharacters[randomInt]);
};
